# Generated by Django 3.1 on 2020-09-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200827_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_gender', models.CharField(max_length=15)),
                ('customer_designation', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dob_date', models.DateField()),
                ('password', models.CharField(max_length=500)),
                ('imgc', models.ImageField(upload_to='shop/customer')),
            ],
        ),
    ]
