# Generated by Django 3.1.1 on 2020-10-10 17:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fertilizers', 'Fertilizers'), ('Agri Machinery', 'Agri Machinery'), ('Pesticide', 'Pesticide'), ('Seeds', 'Seeds'), ('Gardennig', 'Gardennig')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_made',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
