# Generated by Django 3.1.1 on 2020-10-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201012_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
