# Generated by Django 3.1.1 on 2020-10-22 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201012_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(choices=[('Rotavetor Cultivation', 'Rotavetor Cultivation'), ('Cultivation', 'Cultivation'), ('Wet Field', 'Cultivation of Wet Field'), ('Irrigation', 'Irrigation'), ('Trolley', 'Trolley')], default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Unit', models.CharField(choices=[('Bheega', 'Bheega'), ('Mandi', 'Mandi'), ('Hour', 'Hour'), ('Minute', 'Minute'), ('Kilo Meter', 'Kilo Meter')], default='', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
    ]
