# Generated by Django 3.1.1 on 2020-10-13 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(choices=[('Rotavetor Cultivation', 'Rotavetor Cultivation'), ('Cultivation', 'Cultivation'), ('Wet Field', 'Cultivation of Wet Field'), ('Irrigation', 'Irrigation'), ('Trolley', 'Trolley')], default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Unit', models.CharField(choices=[('Bheega', 'Bheega'), ('Mandi', 'Mandi'), ('Hour', 'Hour'), ('Minute', 'Minute')], default='', max_length=50)),
            ],
        ),
    ]
